learning_log/urls.py
from django.contrib import admin
from django.urls import include,path
#from learning_logs import views
#from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    #url(r'',include('learning_logs.urls', namespace='learning_logs')),
    path('',include('learning_logs.urls')),
#    path('topics/',views.topics,name='topics'),
]

"""
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'',include('learning_logs.urls', namespace='learning_logs')),
]

"""

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url
from django.urls import include,path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics,name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
#    path('',views.index, name='index')
#    path('topics/',views.topics,name='topics'),
]

users/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
#    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
#    url(r'^new_topic/$', views.new_topic, name='new_topic'),
#   url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
#    path('',views.index, name='index')
#    path('topics/',views.topics,name='topics'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """用户学习主题"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    """教材错误，见https://jingyan.baidu.com/article/67508eb409cfb49ccb1ce446.html"""
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""

        return self.text[:50] + "..."
    

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

def index(request):
    """index"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit = False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}
    return render(request, 'learning_logs/new_topic.html',context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic':topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html',context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form':form}
    return render(request,'users/register.html',context)
            

learning_logs/templates/backup/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

  	<title>Learning Log</title>

  	{% bootstrap_css %}
  	{% bootstrap_javascript %}

  </head>

  <body>
  	
  	<!-- Static navbar -->
  	<nav class="navbar navbar-default navbar-static-top">
  		<div class="container">

  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed"
  					data-toggle="collapse" data-target="#navbar"
  					aria-expanded="fasle" aria-controls="navbar">
  				</button>
  				<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
  				Learning Log</a>		
  			</div>

  			<div class="collapse navbar-collapse" id="navbaSupportedContent">
  				<ul class="navbar-nav mr_auto">
  					<a class="navbar-brand" href="{% url 'learning_logs:topics' %}">Topics</a>
  				</ul>
  			
  				<ul class="nav navbar-nav navbar-right">
  					{% if user.is_authenticated %}
  				 		<li><a>Hello, {{ user.username }}.</a></li>
  				  		<li><a href="{% url 'users:logout' %}">Log out</a></li>
  					{% else %}
  				  		<li><a href="{% url 'users:register' %}">Register</a></li>
  				 	 	<li><a href="{% url 'users:login' %}">Log in</a></li>
  					{% endif %}  				
  				</ul>
  			</div><!--/.nav-collapse -->
  		</div>
  		
  	</nav>

  	<div class="container">

  		<div class="page-header">
  			{% block header %}{% endblock header %}  			
  		</div>
   		<div>
  			{% block content %}{% endblock content %}  			
  		</div> 			
  		
  	</div><!-- /container-->
  </body>
 </html>

learning_logs/templates/backup/base22.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

  	<title>Learning Log</title>

  	{% bootstrap_css %}
  	{% bootstrap_javascript %}

  </head>

  <body>
  	
  	<!-- Static navbar -->
  	<nav class="navbar navbar-default navbar-static-top">
  		<div class="container">

  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed"
  					data-toggle="collapse" data-target="#navbar"
  					aria-expanded="fasle" aria-controls="navbar">
  				</button>
  				<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
  				Learning Log</a>			
  			</div>

  			<div class="navbar-toggle collapsed">
  				<ul class="nav navbar-nav">
  					<li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
  				</ul>
  			
  				<ul class="nav navbar-nav navbar-right">
  					{% if user.is_authenticated %}
  				 		<li><a>Hello, {{ user.username }}.</a></li>
  				  		<li><a href="{% url 'users:logout' %}">Log out</a></li>
  					{% else %}
  				  		<li><a href="{% url 'users:register' %}">Register</a></li>
  				 	 	<li><a href="{% url 'users:login' %}">Log in</a></li>
  					{% endif %}  				
  				</ul>
  			</div><!--/.nav-collapse -->
  		</div>
  		
  	</nav>

  	<div class="container">

  		<div class="page-header">
  			{% block header %}{% endblock header %}  			
  		</div>
   		<div>
  			{% block content %}{% endblock content %}  			
  		</div> 			
  		
  	</div><!-- /container-->
  </body>
 </html>

learning_logs/templates/backup/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a></p>
  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' >
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/backup/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<div class="jumbotron">
		<h1>Track your learning.</h1>		
	</div>
{% endblock header %}

{% block content %}
	<h2>
		<a href="{% url 'users:register' %}">Register an account</a> to make
		your own Learning Log, and list the topics you are learning about.
	</h2>
	<h2>
		Whenever you learn something new about a topic, make an entry
		summarizing what you are learning.
	</h2>
{% endblock content %}

learning_logs/templates/backup/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a></p>
  <p>Add a new entry:</p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' >
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
  </form>

{% endblock content %}

learning_logs/templates/backup/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

	<form action="{% url 'learning_logs:new_topic' %}" method='post' >
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button name="submit" class="btn btn-primary">add topic</button>
		{% endbuttons %}
    
  </form>

{% endblock content %}

learning_logs/templates/backup/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>

  
  {% for entry in entries %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
              <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
            </small>
          </h3>          
        </div>
        <div class="panel-body">
          {{ entry.text|linebreaks }}          
        </div>
      </div><!-- panel -->
      {% empty %}
        No entries have been added yet.
    {% endfor %}

{% endblock content %}

learning_logs/templates/backup/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

  <u1>
    {% for topic in topics %}
      <li>
	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
      {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
  </u1>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

  	<title>Learning Log</title>

  	{% bootstrap_css %}
  	{% bootstrap_javascript %}

  </head>

  <body>
  	
  	<!-- Static navbar -->
  	<nav class="navbar navbar-default navbar-static-top">
  		<div class="container">

  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed"
  					data-toggle="collapse" data-target="#mynavbar"
  					aria-expanded="fasle" aria-controls="navbar">
  				</button>
  				<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
  				Learning Log</a>		
  			</div>

  			<div class="collapse navbar-collapse" id="mynavbar">
<!--   				<ul class="navbar-nav mr_auto">
  					<a class="navbar-brand" href="{% url 'learning_logs:topics' %}">Topics</a>
  				</ul> -->
  			
  				<ul class="nav navbar-nav navbar-right">
  					{% if user.is_authenticated %}
  				 		<li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
  				  	<li><a href="{% url 'users:logout' %}">Log out</a></li>
  					{% else %}
  				  	<li><a href="{% url 'users:register' %}">Register</a></li>
  				 	 	<li><a href="{% url 'users:login' %}">Log in</a></li>
  					{% endif %}  				
  				</ul>
  			</div><!--/.nav-collapse -->
  		</div>
  		
  	</nav>

  	<div class="container">

  		<div class="page-header">
  			{% block header %}{% endblock header %}  			
  		</div>
   		<div>
  			{% block content %}{% endblock content %}  			
  		</div> 			
  		
  	</div><!-- /container-->
  </body>
 </html>

learning_logs/templates/learning_logs/base22.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

  	<title>Learning Log</title>

  	{% bootstrap_css %}
  	{% bootstrap_javascript %}

  </head>

  <body>
  	
  	<!-- Static navbar -->
  	<nav class="navbar navbar-default navbar-static-top">
  		<div class="container">

  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed"
  					data-toggle="collapse" data-target="#navbar"
  					aria-expanded="fasle" aria-controls="navbar">
  				</button>
  				<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
  				Learning Log</a>			
  			</div>

  			<div class="navbar-toggle collapsed">
  				<ul class="nav navbar-nav">
  					<li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
  				</ul>
  			
  				<ul class="nav navbar-nav navbar-right">
  					{% if user.is_authenticated %}
  				 		<li><a>Hello, {{ user.username }}.</a></li>
  				  		<li><a href="{% url 'users:logout' %}">Log out</a></li>
  					{% else %}
  				  		<li><a href="{% url 'users:register' %}">Register</a></li>
  				 	 	<li><a href="{% url 'users:login' %}">Log in</a></li>
  					{% endif %}  				
  				</ul>
  			</div><!--/.nav-collapse -->
  		</div>
  		
  	</nav>

  	<div class="container">

  		<div class="page-header">
  			{% block header %}{% endblock header %}  			
  		</div>
   		<div>
  			{% block content %}{% endblock content %}  			
  		</div> 			
  		
  	</div><!-- /container-->
  </body>
 </html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a></p>
  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' >
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<div class="jumbotron">
		<h1>Track your learning.</h1>		
	</div>
{% endblock header %}

{% block content %}
	<h2>
		<a href="{% url 'users:register' %}">Register an account</a> to make
		your own Learning Log, and list the topics you are learning about.
	</h2>
	<h2>
		Whenever you learn something new about a topic, make an entry
		summarizing what you are learning.
	</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a></p>
  <p>Add a new entry:</p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' >
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

	<form action="{% url 'learning_logs:new_topic' %}" method='post' >
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button name="submit" class="btn btn-primary">add topic</button>
		{% endbuttons %}
    
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>

  
  {% for entry in entries %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
              <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
            </small>
          </h3>          
        </div>
        <div class="panel-body">
          {{ entry.text|linebreaks }}          
        </div>
      </div><!-- panel -->
      {% empty %}
        No entries have been added yet.
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

  <u1>
    {% for topic in topics %}
      <li>
	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
      {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
  </u1>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

	<form method="post" action="{% url 'users:login' %}">
	{% csrf_token %}
	{{ form.as_p }}

	{% buttons %}
		<button name="submit" class="btn btn-primary">log in</button>
	{% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
  </form>

{% endblock content %}